name: my_first_get_x
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.5 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  dio: ^5.3.3
  get: 4.6.6
  flutter: 
    sdk: flutter
  flutter_svg: ^2.0.9
  google_fonts: ^6.1.0
  flutter_screenutil: ^5.9.0
  popover: ^0.2.8+2

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf


